language: csharp
solution: School/School.sln
install:
  - nuget restore School/School.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release School/School.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./School/School.Data.Tests/bin/Release/School.Data.Tests.dll
